"""lineage edge

Revision ID: 01588ea27ac4
Revises: 30fe132f91ee
Create Date: 2026-09-05 07:55:15.891712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01588ea27ac4'
down_revision: Union[str, Sequence[str], None] = '30fe132f91ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_kind', sa.String(), nullable=False),
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_kind', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lineage_edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_edge_from_id'), ['from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_edge_from_kind'), ['from_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineage_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_edge_from_kind'))
        batch_op.drop_index(batch_op.f('ix_lineage_edge_from_id'))

    op.drop_table('lineage_edge')
    # ### end Alembic commands ###
