"""initial schema

Revision ID: 171207cc8819
Revises:
Create Date: 2026-09-04 19:39:19.984268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bhumi.storage.db.types


# revision identifiers, used by Alembic.
revision: str = '171207cc8819'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assay_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domain_pack_version', sa.Integer(), nullable=False),
    sa.Column('state_counts', sa.JSON(), nullable=False),
    sa.Column('gate_failure_counts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('assay_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assay_run_doc_id'), ['doc_id'], unique=False)

    op.create_table('candidate_fact',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('entity_raw', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('metric_raw', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=True),
    sa.Column('value_raw', sa.String(), nullable=False),
    sa.Column('value', bhumi.storage.db.types.DecimalString(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_source', sa.String(), nullable=True),
    sa.Column('qualifiers', sa.JSON(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('domain_type', sa.String(), nullable=True),
    sa.Column('domain_pack_version', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('gate_results', sa.JSON(), nullable=False),
    sa.Column('failed_gate', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('assay_run_id', sa.String(), nullable=False),
    sa.Column('reeval_count', sa.Integer(), nullable=False),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_fact_assay_run_id'), ['assay_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_state'), ['state'], unique=False)

    op.create_table('document_ast',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('ast_path', sa.String(), nullable=False),
    sa.Column('ast_hash', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('page_raster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_raster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_raster_doc_id'), ['doc_id'], unique=False)

    op.create_table('read_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tier_counts', sa.JSON(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('read_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_run_doc_id'), ['doc_id'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_doc_id'), ['doc_id'], unique=False)

    op.create_table('source_registry',
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('doc_kind', sa.String(), nullable=False),
    sa.Column('authority_rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('coalfield', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('vault_ref', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    with op.batch_alter_table('source_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_registry_doc_id'), ['doc_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_registry_doc_id'))

    op.drop_table('source_registry')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_doc_id'))

    op.drop_table('review_queue')
    with op.batch_alter_table('read_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_run_doc_id'))

    op.drop_table('read_run')
    with op.batch_alter_table('page_raster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_raster_doc_id'))

    op.drop_table('page_raster')
    op.drop_table('document_ast')
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_fact_state'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_metric_key'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_doc_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_assay_run_id'))

    op.drop_table('candidate_fact')
    with op.batch_alter_table('assay_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assay_run_doc_id'))

    op.drop_table('assay_run')
    # ### end Alembic commands ###
