"""graph tables

Revision ID: 30fe132f91ee
Revises: e158a3355f2e
Create Date: 2026-09-04 22:57:02.079212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fe132f91ee'
down_revision: Union[str, Sequence[str], None] = 'e158a3355f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('dst', sa.String(), nullable=False),
    sa.Column('rel', sa.String(), nullable=False),
    sa.Column('trust_layer', sa.String(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('fact_id', sa.String(), nullable=True),
    sa.Column('domain_pack_version', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edge_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edge_dst'), ['dst'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edge_rel'), ['rel'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edge_src'), ['src'], unique=False)

    op.create_table('graph_node',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('graph', sa.String(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    with op.batch_alter_table('graph_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_node_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_node_graph'), ['graph'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_node_label'), ['label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_node_label'))
        batch_op.drop_index(batch_op.f('ix_graph_node_graph'))
        batch_op.drop_index(batch_op.f('ix_graph_node_doc_id'))

    op.drop_table('graph_node')
    with op.batch_alter_table('graph_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edge_src'))
        batch_op.drop_index(batch_op.f('ix_graph_edge_rel'))
        batch_op.drop_index(batch_op.f('ix_graph_edge_dst'))
        batch_op.drop_index(batch_op.f('ix_graph_edge_doc_id'))

    op.drop_table('graph_edge')
    # ### end Alembic commands ###
