"""published statement

Revision ID: 81ae3ff0e878
Revises: bbfb48311e57
Create Date: 2026-09-05 14:00:28.422390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bhumi.storage.db.types


# revision identifiers, used by Alembic.
revision: str = '81ae3ff0e878'
down_revision: Union[str, Sequence[str], None] = 'bbfb48311e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_statement',
    sa.Column('statement_id', sa.String(), nullable=False),
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('qualifiers', sa.JSON(), nullable=False),
    sa.Column('value', bhumi.storage.db.types.DecimalString(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('statement_id')
    )
    with op.batch_alter_table('published_statement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_statement_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_statement_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_statement_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_statement_metric_key'), ['metric_key'], unique=False)
    # ### end Alembic commands ###
    # NOTE: hand-edited — autogenerate wanted to drop chunk_fts and its
    # FTS5 shadow tables (chunk_fts_content/idx/docsize/config/data).
    # Those are real, raw-sqlite3-created virtual tables (storage/text/
    # fts5.py), invisible to SQLAlchemy's ORM metadata, so autogenerate
    # sees them as "removed" every time. Dropping them here would
    # silently destroy the real search index on every upgrade. See
    # PROVENANCE.md.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('published_statement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_statement_metric_key'))
        batch_op.drop_index(batch_op.f('ix_published_statement_fact_id'))
        batch_op.drop_index(batch_op.f('ix_published_statement_entity_id'))
        batch_op.drop_index(batch_op.f('ix_published_statement_doc_id'))

    op.drop_table('published_statement')
    # ### end Alembic commands ###
