"""chunk table

Revision ID: bbfb48311e57
Revises: 01588ea27ac4
Create Date: 2026-09-05 08:00:46.275487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfb48311e57'
down_revision: Union[str, Sequence[str], None] = '01588ea27ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('context_prefix', sa.String(), nullable=True),
    sa.Column('indexed_text', sa.String(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunk_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunk_parent_id'))
        batch_op.drop_index(batch_op.f('ix_chunk_doc_id'))
        batch_op.drop_index(batch_op.f('ix_chunk_classification'))

    op.drop_table('chunk')
    # ### end Alembic commands ###
