"""candidate_fact value_kind

Revision ID: c91f1362e8bc
Revises: 171207cc8819
Create Date: 2026-09-04 21:32:13.729120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91f1362e8bc'
down_revision: Union[str, Sequence[str], None] = '171207cc8819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_kind', sa.String(), nullable=False, server_default='point'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.drop_column('value_kind')

    # ### end Alembic commands ###
