"""audit log and sealed package

Revision ID: dc5c060b12dc
Revises: 81ae3ff0e878
Create Date: 2026-09-05 15:03:02.969728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5c060b12dc'
down_revision: Union[str, Sequence[str], None] = '81ae3ff0e878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tool'), ['tool'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('sealed_package',
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('principal_subject', sa.String(), nullable=False),
    sa.Column('max_classification', sa.JSON(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('package_id')
    )
    with op.batch_alter_table('sealed_package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sealed_package_content_hash'), ['content_hash'], unique=False)
    # ### end Alembic commands ###
    # NOTE: hand-edited — autogenerate wants to drop chunk_fts and its
    # FTS5 shadow tables every time (real, raw-sqlite3-created virtual
    # tables invisible to SQLAlchemy's ORM metadata). See the identical
    # note in 81ae3ff0e878_published_statement.py and PROVENANCE.md.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sealed_package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sealed_package_content_hash'))

    op.drop_table('sealed_package')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_tool'))
        batch_op.drop_index(batch_op.f('ix_audit_log_subject'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
