"""fact ledger

Revision ID: e158a3355f2e
Revises: c91f1362e8bc
Create Date: 2026-09-04 22:38:22.658805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bhumi.storage.db.types


# revision identifiers, used by Alembic.
revision: str = 'e158a3355f2e'
down_revision: Union[str, Sequence[str], None] = 'c91f1362e8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.Column('fact_identity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('qualifiers', sa.JSON(), nullable=False),
    sa.Column('value_kind', sa.String(), nullable=False),
    sa.Column('value', bhumi.storage.db.types.DecimalString(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('system_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('system_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('fact_id')
    )
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_fact_identity'), ['fact_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_system_to'), ['system_to'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_system_to'))
        batch_op.drop_index(batch_op.f('ix_fact_metric_key'))
        batch_op.drop_index(batch_op.f('ix_fact_fact_identity'))
        batch_op.drop_index(batch_op.f('ix_fact_entity_id'))

    op.drop_table('fact')
    # ### end Alembic commands ###
